//go:build !ignore_autogenerated

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func (in *DataPipeline) DeepCopyInto(out *DataPipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DataPipeline) DeepCopy() *DataPipeline {
	if in == nil {
		return nil
	}
	out := new(DataPipeline)
	in.DeepCopyInto(out)
	return out
}

func (in *DataPipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DataPipelineList) DeepCopyInto(out *DataPipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataPipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DataPipelineList) DeepCopy() *DataPipelineList {
	if in == nil {
		return nil
	}
	out := new(DataPipelineList)
	in.DeepCopyInto(out)
	return out
}

func (in *DataPipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DataPipelineSpec) DeepCopyInto(out *DataPipelineSpec) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

func (in *DataPipelineSpec) DeepCopy() *DataPipelineSpec {
	if in == nil {
		return nil
	}
	out := new(DataPipelineSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DataPipelineStatus) DeepCopyInto(out *DataPipelineStatus) {
	*out = *in
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessTime != nil {
		in, out := &in.LastSuccessTime, &out.LastSuccessTime
		*out = (*in).DeepCopy()
	}
}

func (in *DataPipelineStatus) DeepCopy() *DataPipelineStatus {
	if in == nil {
		return nil
	}
	out := new(DataPipelineStatus)
	in.DeepCopyInto(out)
	return out
}
